services:
  - type: web
    name: mozaic-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false